services:
    phpsed.cache.listener:
        class: Phpsed\Cache\EventListener\CacheListener
        arguments:
            - '@annotation_reader'
            - '@service_container'
        tags:
            -
                name: kernel.event_subscriber
